### ISSUE TITLE
无法编译为windows可执行文件

### ISSUE THREAD

**Issue by dogfight360** [eycorsican/go-tun2socks#1]
修改编译参数(Make文件,行68)为
cd $(CMDDIR) && GOARCH='386' GOOS='windows' $(GOBUILD) -o $(BUILDDIR)/$(PROGRAM) -v

执行make build编译后报如下错误

# github.com/eycorsican/go-tun2socks/cmd/tun2socks
./main.go:44:2: undefined: lwip.Setup
./main.go:58:2: undefined: lwip.RegisterOutputFn
./main.go:71:10: undefined: lwip.Input
make: *** [build] Error 2

**Comment by noeruh** [comment]
@dogfight360 粗略搞了下，暂时可以用这个分支来编译 windows 程序：https://github.com/eycorsican/go-tun2socks/tree/windows ，我得另找时间合并进 master。

因为项目用到了 cgo，在其它平台上交叉编译需要用相应的工具链，比如 MinGW。我推荐你用 xgo：https://github.com/karalabe/xgo

另外我把现成的可执行程序上传了，你要用可以直接下载：https://github.com/eycorsican/go-tun2socks/blob/windows/tun2socks-windows.zip

运行所需的命令大概这样子：
```
tun2socks.exe -dnsServer 1.1.1.1,223.5.5.5 -proxyServer 1.2.3.4:1086 -tunAddr 10.0.0.1 -tunGw 10.0.0.2 -tunMask 255.255.255.0 -tunName tap0901:tun1:10.0.0.1:10.0.0.0:255.255.255.0

route add 1.2.3.4 192.168.1.1 metric 5
route add 0.0.0.0 mask 0.0.0.0 10.0.0.2 metric 6
```
具体可参考这里：https://code.google.com/archive/p/badvpn/wikis/tun2socks.wiki

**Comment by eycorsican** [comment]
@dogfight360 粗略搞了下，暂时可以用这个分支来编译 windows 程序：https://github.com/eycorsican/go-tun2socks/tree/windows ，我得另找时间合并进 master。

因为项目用到了 cgo，在其它平台上交叉编译需要用相应的工具链，比如 MinGW。我推荐你用 xgo：https://github.com/karalabe/xgo

另外我把现成的可执行程序上传了，你要用可以直接下载：https://github.com/eycorsican/go-tun2socks/blob/windows/tun2socks-windows.zip

运行所需的命令大概这样子：
```
tun2socks.exe -dnsServer 1.1.1.1,223.5.5.5 -proxyServer 1.2.3.4:1086 -tunAddr 10.0.0.1 -tunGw 10.0.0.2 -tunMask 255.255.255.0 -tunName tap0901:tun1:10.0.0.1:10.0.0.0:255.255.255.0

route add 1.2.3.4 192.168.1.1 metric 5
route add 0.0.0.0 mask 0.0.0.0 10.0.0.2 metric 6
```
具体可参考这里：https://code.google.com/archive/p/badvpn/wikis/tun2socks.wiki

**Comment by dogfight360** [comment]
exe测试在win10正常运行
编译为win还在一头雾水中.还是等一个完整的教程吧┗( T﹏T )┛
