### ISSUE TITLE
TAP网卡默认路由被删除

### ISSUE THREAD

**Issue by Fndroid** [eycorsican/go-tun2socks#103]
``-tunGw``和``-tunDns``似乎没有正确设置到TAP网卡里

![image](https://user-images.githubusercontent.com/16091562/76086458-13122480-5fef-11ea-84ec-77ccad6031c2.png)

**Comment by eycorsican** [comment]
10.0.0.0 可以配作 IP 的吗？我也不清楚，手头没 windows 没法验证

**Comment by Fndroid** [comment]
windows上是可以的，我也试了把10.0.0.0改成10.0.01，地址改成10.0.0.2也不行

**Comment by cpu100** [comment]
Win10 系统， `-tunGw` 确实没有显示到网卡状态上，但是不影响数据捕获。可能，这个 GW 只是个虚拟的网关，只是 TAP 用来筛选数据包的设定，你的系统上有一条指向这个虚拟网关的路由，TAP就可以正常捕获。

**Comment by Fndroid** [comment]
@cpu100 感谢提点。

@eycorsican  设置应该是没问题的，但是发现go-tun2socks会把默认的TAP路由删掉，不知道这是为什么。

安装完TAP之后，启动go-tun2socks之前：
![image](https://user-images.githubusercontent.com/16091562/77600526-2d328900-6f43-11ea-96b1-03170b233689.png)

启动go-tun2socks之后：
![image](https://user-images.githubusercontent.com/16091562/77600648-7f73aa00-6f43-11ea-992b-f3607fe95228.png)

**Comment by Fndroid** [comment]
找到原因了，是DHCP造成的，应该是系统行为
