### ISSUE TITLE
tcp data transfer sample

### ISSUE THREAD

**Issue by caleb-letsgo** [eycorsican/go-tun2socks#107]
Do you have a sample program: once the tun is started, listen on it and receive the connection, passing the data?
No examples were found, and no useful documentation was found.

**Comment by cpu100** [comment]
[tcpHandler](https://github.com/eycorsican/go-tun2socks/blob/eebb391cf216724da69c9594f9ed46fbce958661/proxy/socks/tcp.go#L88)
