### ISSUE TITLE
问一个“低级”问题

### ISSUE THREAD

**Issue by luckypoem** [eycorsican/go-tun2socks#111]
hi.

我在mac上运行：
sudo $GOPATH/src/github.com/eycorsican/go-tun2socks/build/tun2socks -proxyServer 127.0.0.1:1080 -proxyType socks -tunAddr 10.255.0.2 -tunGw 10.255.0.1 -tunName tun1

显示：
2020/04/08 22:40:05 new proxy connection to 151.101.0.133:443
2020/04/08 22:40:07 new proxy connection to 151.101.0.133:443
2020/04/08 22:40:08 new proxy connection to 140.82.114.26:443
2020/04/08 22:40:10 new proxy connection to 151.101.0.133:443
2020/04/08 22:40:11 new proxy connection to 104.248.15.162:31879
2020/04/08 22:40:13 new proxy connection to 174.137.50.203:2255
2020/04/08 22:40:32 new proxy connection to 174.137.50.203:2255
2020/04/08 22:40:33 new proxy connection to 174.137.50.203:2255
2020/04/08 22:40:41 new proxy connection to 174.137.50.203:2255
2020/04/08 22:40:49 new proxy connection to 174.137.50.203:2255
2020/04/08 22:40:51 new proxy connection to 104.248.15.162:31879
2020/04/08 22:40:59 new proxy connection to 174.137.50.203:2255
2020/04/08 22:41:06 new proxy connection to 174.137.50.203:2255
2020/04/08 22:41:14 new proxy connection to 174.137.50.203:2255
2020/04/08 22:41:24 new proxy connection to 174.137.50.203:2255
2020/04/08 22:41:31 new proxy connection to 104.248.15.162:31879
2020/04/08 22:41:34 new proxy connection to 174.137.50.203:2255
2020/04/08 22:41:44 new proxy connection to 174.137.50.203:2255
2020/04/08 22:41:55 new proxy connection to 174.137.50.203:2255
2020/04/08 22:42:01 new proxy connection to 17.57.144.20:5223
2020/04/08 22:42:02 new proxy connection to 174.137.50.203:2255
2020/04/08 22:42:10 new proxy connection to 174.137.50.203:2255

这些ip地址是哪里来的？这是正常的吗？还是我被hack了？

抱歉，问了一个“低级”问题。
非常感谢答复。

**Comment by iamluodong** [comment]
这明显是通过你的1080代理端口出去的。

**Comment by luckypoem** [comment]
@iamluodong 
是啊，是通过我本地机器mac上的1080端口出去的，我不明白“这些ip地址是哪里来的？这是正常的吗？”，能正面回答yes或no吗？
这些ip地址中，没有我的vps的ip.

**Comment by ushuz** [comment]
> 这些ip地址是哪里来的？这是正常的吗？还是我被hack了？

DNS 解析来的，正常，不是被 hack
