### ISSUE TITLE
请问如何配置路由？在线求解答

### ISSUE THREAD

**Issue by ws826402696** [eycorsican/go-tun2socks#113]
我的socks server 是127.0.0.1:1080 , 请问配置路由命令怎么写?

**Comment by ws826402696** [comment]
主要问题是由于server是 127.0.0.1 配置路由表的时候怀疑 会和默认的回环路由冲突

**Comment by imgk** [comment]
参考这个https://github.com/Dreamacro/clash/issues/555，用 owner 区分不同应用流量应该就可以了
