### ISSUE TITLE
UDP错误

### ISSUE THREAD

**Issue by dogfight360** [eycorsican/go-tun2socks#116]
随机出现错误
UDP流量,大概0-100+KB/S
有时候不同跑一天都没事,有时候一两小时甚至没几分钟就报错

release的v1.16.8及最新源码(Commits on Apr 9, 2020)编译均出现该错误
日志:

panic: runtime error: slice bounds out of range

goroutine 271 [running]:
github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).fetchUDPInput(0x113f8300, 0x543c20, 0x116c4a80, 0x543f60, 0x11454a50)
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:81 +0x37d
created by github.com/eycorsican/go-tun2socks/proxy/socks.(*udpHandler).connectInternal
        /ext-go/1/src/github.com/eycorsican/go-tun2socks/proxy/socks/udp.go:152 +0x641

**Comment by dogfight360** [comment]
UDP仍然有问题,但是现在程序不会崩溃,也没有错误输出
开的-loglevel debug依然没有
出问题概率仍然比较随机
测试的游戏apex legends及battlefield 1

表现为游戏玩着玩着就掉线


附件内的html文件为截取的最后掉线前的封包的记录(蓝色为发送,粉色为接收)
可以看到出现问题后游戏在不停往服务器发包.但是没有任何回应.接着就是超时掉线
[report1.zip](https://github.com/eycorsican/go-tun2socks/files/4697615/report1.zip)

已测试多次,能确定是代码部分问题
可排除服务器线路抽风
同样网络同样服务器线路
使用另一个T2S项目(https://github.com/yinghuocho/gotun2socks)
同时游戏玩一晚上是一直正常的

**Comment by eycorsican** [comment]
试下调大 UDP 超时 `-udpTimeout 2h0m0s`

**Comment by dogfight360** [comment]
> 试下调大 UDP 超时 `-udpTimeout 2h0m0s`

OK,今晚再试试超时2小时.上面掉线是设置了超时10分钟的

**Comment by eycorsican** [comment]
@dogfight360 对应你前面提到的 UDP 出错问题，再做了点修改，你用最新的 master 自己编译一个试试

**Comment by dogfight360** [comment]
设置为2小时超时,情况依旧

**Comment by dogfight360** [comment]
最新的代码已经没有问题.测了一天.稳稳地
