### ISSUE TITLE
如何编译在IOS里使用的framework?

### ISSUE THREAD

**Issue by ameue** [eycorsican/go-tun2socks#12]
用gomobile bind --target=ios github.com/eycorsican/go-tun2socks/tun/ 感觉不对，是个空framework。应该怎样正确的编译呢？
看了这个https://github.com/eycorsican/go-tun2socks/issues/8#issue-375416238 后面都在说内存了。

**Comment by eycorsican** [comment]
参考：https://github.com/eycorsican/go-tun2socks-ios

**Comment by FatChou** [comment]
make出来的只有armv7架构。

**Comment by FatChou** [comment]
Tun2socksStartShadowsocks传入一个不支持的加密方式(chacha20)的时候，进程就挂了

**Comment by FatChou** [comment]
在iPhone 5上试了下，把framework添加到工程里，在不不import的情况下运行，PacketTunnel运行不起来，iPhone X可以，应该也是内存的问题吧

**Comment by FatChou** [comment]
make文件加上ios/arm64后，编译出armv7 arm64库，但是在iPhone 5这样的设备上只要把包添加到工程，不import的情况，PacketTunnel都运行不起来

**Comment by eycorsican** [comment]
能提供相关的错误信息吗？

**Comment by FatChou** [comment]
抓不到错误信息，启动PacketTunnel就挂。有没有什么办法能看到错误信息呢？

**Comment by FatChou** [comment]
lipo -info Tun2socks.framework/Tun2socks 查看了下framework的指令集
Architectures in the fat file: Tun2socks.framework/Tun2socks are: armv7 arm64
