### ISSUE TITLE
Stop and restart will result in `fail to dial UDP > address <nil>: missing port`

### ISSUE THREAD

**Issue by Vigilans** [eycorsican/go-tun2socks#126]
这个问题是使用[mellow-io/mellow-core](https://github.com/mellow-io/mellow-core)的go-tun2socks版本时出现的，更换了[mellow-io/go-tun2socks](https://github.com/mellow-io/go-tun2socks/releases/tag/v1.0.8)的最新版本core仍未解决。

在Linux下运行mellow core时，第一次能正常运行成功，但在输入Ctrl + C停止后，第二次启动极有可能会出现udp dial > address \<nil\>: port missing 的bug，如下图所示：

![image](https://user-images.githubusercontent.com/20227484/87807818-4b721b00-c88b-11ea-8061-af346652057e.png)

一般遇到这种情况，需要重启后才能恢复正常。不过，在第一次运行停止后，放置一段时间或做一些玄学操作（几个月前开始出现的bug，忘了做什么操作能貌似避免这个问题……），第二次运行能够成功。

由于所用的Linux是工作机，环境比较复杂，在其他环境可能不能复现。如有兴趣解决问题并有需要的话，可以提供本机的ssh能力。

### Mellow core: go-tun2socks 版本

1.08

### 使用操作系统类型以及版本

Deepin 15.11, Based on Debian 9

**Comment by eycorsican** [comment]
日志第一行那里应该是一个 IP 地址，显示 `default` 就要会出问题
