### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by ggg17226** [eycorsican/go-tun2socks#132]
os: openwrt r13342-e35e40ad82
kernel:5.4.42
cpu: amd 3500x
ram: 16g ddr4

musl gcc version info:
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-10ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2)

go version: go version go1.14.6 linux/amd64

不管是master还是v1.16.9都在我自己编译的x86 openwrt下频繁崩溃
崩溃日志见文件
[tun2socks-error-log.zip](https://github.com/eycorsican/go-tun2socks/files/4978228/tun2socks-error-log.zip)

**Comment by eycorsican** [comment]
试一下 `bugfix` 分支

**Comment by ggg17226** [comment]
跑了半小时没崩，应该是解决了

**Comment by ggg17226** [comment]
刚说完就又挂了

**Comment by ggg17226** [comment]
[tun2socks.4396382d4d40f63b038ce5c5df4c4cd6d27d8900.zip](https://github.com/eycorsican/go-tun2socks/files/4980455/tun2socks.4396382d4d40f63b038ce5c5df4c4cd6d27d8900.zip)

**Comment by eycorsican** [comment]
> [tun2socks.4396382d4d40f63b038ce5c5df4c4cd6d27d8900.zip](https://github.com/eycorsican/go-tun2socks/files/4980455/tun2socks.4396382d4d40f63b038ce5c5df4c4cd6d27d8900.zip)

这个日志不是 bugfix 编译出来的啊。
