### ISSUE TITLE
unsupported proxy type

### ISSUE THREAD

**Issue by frustreated** [eycorsican/go-tun2socks#134]
tun2socks.exe  -tunAddr 10.0.236.2 -tunMask 255.255.255.0 -tunGw 10.0.236.1 -tunName "SSTAP" -tunDns 114.114.114.114,8.8.8.8 -proxyType socks
2020/07/29 10:09:20 TAP device name: SSTAP
2020/07/29 10:09:20 Set SSTAP with net/mask: 10.0.236.2/255.255.255.0 through DHCP
2020/07/29 10:09:20 Set SSTAP with DNS: 114.114.114.114,8.8.8.8 through DHCP
2020/07/29 10:09:20 **unsupported proxy type**

**Comment by eycorsican** [comment]
I believe you're not running binaries download from the releases page.
