### ISSUE TITLE
被限速了，下行最多跑100Mbps

### ISSUE THREAD

**Issue by f4nff** [eycorsican/go-tun2socks#142]
直连socks5可以跑270Mps，
但是使用go-tun2socks转发之后，只能跑100Mbps
ubuntu windows 测试都一样，最大被限速在100Mbps

**Comment by f4nff** [comment]
i7-9750H
64G内存，足够跑go-tun2socks了吗？
测来测去，就是go-tun2socks程序问题，
早期的outline-ios（基于go-tun2socks）版本，也是限速，限速在30Mbps，
最近升级之后，才没限速了，

**Comment by f4nff** [comment]
这项目垃圾，
https://github.com/yinghuocho/gotun2socks
直接跑满速

**Comment by lizenghui** [comment]
关注一下！我试试测一下速度
