### ISSUE TITLE
go-tun2socks能不能实现dns分流功能

### ISSUE THREAD

**Issue by OnlyCharacter** [eycorsican/go-tun2socks#146]
实现像v2那样国内域名用国内dns，国外域名用国外dns。或者把dns处理全交给v2处理，让v2选择dns。

**Comment by eycorsican** [comment]
https://github.com/mellow-io/mellow

**Comment by OnlyCharacter** [comment]
> https://github.com/mellow-io/mellow

实际使用mellow遇到一些问题，似乎会破坏ipv6的路由。
在Windows系统中，ipv4和ipv6都正常连接，但用完mellow再关闭，ipv6就连不上网络了。
而且我用mellow碰上了dns死循环的问题。
