### ISSUE TITLE
使用内置的v2ray好像udp转发有问题

### ISSUE THREAD

**Issue by doraeden** [eycorsican/go-tun2socks#15]
用的最新源码编译的版本，环境是windows 10 x64
使用tun2socks内置的v2ray无法进入吃鸡等需要UDP的游戏，NatTypeTester测试出的NAT类型为Symmetric
如果单独运行v2ray，通过socks5连接到tun2socks则可以正常玩游戏，但是速度会严重下降，使用内置v2ray或者v2ray的socks端口的时候能跑满200M宽带，而通过socks5连接到tun2socks只有50M

**Comment by eycorsican** [comment]
让我正解下你的意思，你是说这种可以正常游戏：
tun2socks(socks) -> (socks inbound)v2ray -> 游戏服务器

而这种不能正常游戏：
tun2socks(v2ray) -> 游戏服务器

对不对？


关于速度，默认设置只跑 50M~60M 不意外，你可以尝试改下这里的配置：https://github.com/eycorsican/go-tun2socks/blob/master/core/tcp_conn.go#L64 ，比如改成 30 的 channel 大小，就应该足以跑满 200M。

**Comment by doraeden** [comment]
是的，我说的是这个意思
改了果然能跑满了

**Comment by ameue** [comment]
outbound使用ss。服务器是ss，没有使用v2ray。
开启服务后，发现只有DNS数据转到ss服务器，UDP数据好像从本地出去了。TCP数据能转发到服务器。
想了解下，这是什么原因？

**Comment by eycorsican** [comment]
目前 tun2socks 的确只实现了 Symmetric NAT，正在准备换成其它类型

**Comment by eycorsican** [comment]
@ameue 看起来是你配置不对，你发问题时最好把相关配置信息、日志都发下，说不定在这过程中你就找到问题所在了

**Comment by ameue** [comment]
应该是配置的问题。但是内存的问题不解决，这问题也就可以不考虑了。

**Comment by sqwwqw5** [comment]
> 目前 tun2socks 的确只实现了 Symmetric NAT，正在准备换成其它类型

可以参考一下Outline，他们实现了restricted cone。

**Comment by eycorsican** [comment]
I am going to close this, and continue to track NAT related issues in #36
