### ISSUE TITLE
socks5 udp延迟会突然变高

### ISSUE THREAD

**Issue by atxiu** [eycorsican/go-tun2socks#16]
使用版本：go-tun2socks 1.82，环境windows 10 x64
代理服务器程序：gost2.6、shadowsocks-libev
游戏：绝地求生
使用tun2socks内置的socks5直连代理服务器，可以正常游戏，但有时延迟会突然飙升一次，然后马上降下来，具体则是在请求某个服务器443端口之后，日志表现如下：
本地gost流，server 为代理服务器
```
2018/11/20 20:45:55 socks.go:465: [socks5-connect] 127.0.0.1:8793 >-< 34.195.78.241:443
2018/11/20 20:46:28 socks.go:693: [socks5-udp] 127.0.0.1:8775 >-< 127.0.0.1:62755
2018/11/20 20:46:28 socks.go:836: [udp-tun] server:prot -> 0 : read tcp 192.168.1.2:8776->server:prot: use of closed network connection
2018/11/20 20:46:28 socks.go:801: [udp-tun] server:prot <- <nil> : read udp [::]:62755: use of closed network connection
2018/11/20 20:46:29 socks.go:626: [socks5-udp] 127.0.0.1:8802 - [::]:62902 BIND ON 127.0.0.1:62902 OK
2018/11/20 20:46:30 socks.go:686: [socks5-udp] 127.0.0.1:8802 <-> 127.0.0.1:62902 [tun: server:16755]
2018/11/20 20:46:30 socks.go:689: [socks5-udp] 127.0.0.1:8802 <-> 127.0.0.1:62902
```
tun2socks 流
```
2018/11/20 20:45:54 new proxy connection for target: tcp:34.195.78.241:443
```
这种延迟高的问题使用本地socks5中转或公网中转也无法解决，但同一台服务器使用tun2socks内置的shadowsocks连接则不会出现这种情况。

**Comment by eycorsican** [comment]
你测一下 v1.8.3

**Comment by atxiu** [comment]
@eycorsican 问题依然存在

**Comment by eycorsican** [comment]
看起来是因为控制 UDP 会话的 TCP 连接被关闭，导致 UDP 会话中断了。从你发出的来的日志看，gost 似乎收到了 io.EOF 而关闭的，这情况下我觉得最有可能是 TCP 连接被中间路由设备发 RST 包了，能在客户端和服务端同时抓包看的话会更加清晰。

Shadowsocks 没出现这种情况大概是因为它没用 TCP 连接来控制 UDP 会话。

**Comment by eycorsican** [comment]
还有就是如果  UDP 会话闲置太长时间的话也会被主动关掉，默认设置的 1 分钟（`-udpTimeout`），你可以调整看看，不过这个设置 SOCKS 跟 Shadowsocks 都是一样的所以我想应该不会是这个问题

**Comment by atxiu** [comment]
好的，我会在合适的时间抓包

**Comment by atxiu** [comment]
大致抓包找到了一些问题，本地网卡在游戏游玩时向某逊服务器443端口请求数据时，不知道是中间丢了还是怎么样，引起retransmission，每次retransmission游戏中延迟就会突然变高，这种可有解决方案？
![image](https://user-images.githubusercontent.com/33857802/48968152-d141b280-f025-11e8-8c4d-d3d42edbc768.png)

**Comment by atxiu** [comment]
事实上我去访问了这个443资源，资源是正常的，会不会是因丢包引起的tcp虚假重传
参考链接：https://www.cnblogs.com/stupidbug/articles/8144236.html

**Comment by eycorsican** [comment]
这是在 TUN 接口上抓的包？10.0.0.2 到 TUN 的传输不应该存在丢包的现象，看起来更像是因为某些原因 tun2socks 把这个 TCP 连接关闭了，但 10.0.0.2 没有收到任何 FIN/RST 包，还在继续尝试发数据，你可以把整段 TCP 流的数据发上来吗？（对着其中一个包点鼠标右键 -> Follow -> TCP  Stream 就可以自动过滤出来）

**Comment by atxiu** [comment]
按你所述操作测试是没有问题的

**Comment by eycorsican** [comment]
那就有理由怀疑数据在中间链路被删改过了，导致TLS解密数据时出错引起 encrypted
alert，然后连接就断了，因为用的是没加密的socks，连接到外部的时候还是最好用加密协议，比如shadowsocks

**Comment by atxiu** [comment]
了解，已设置加密方案，请关闭这个问题
