### ISSUE TITLE
window版本能否提供指定网络适配器功能

### ISSUE THREAD

**Issue by xingplus** [eycorsican/go-tun2socks#20]
windows版本遍历网络适配器后，默认选择了第一个找到的tap0901/tap0801的适配器，能否提供一个选项，供使用者指定适配器，如：-tunName "Another TAP Network Adapter"

**Comment by eycorsican** [comment]
是的，TUN 这块的实现代码非常粗糙，几乎都是复制过来的代码，对于这块我暂时没时间去优化和增加功能（其实是懒和个人没需求），或许 Windows 的实现可以像 macOS 那样换用 [water](https://github.com/songgao/water) 会比较好。

欢迎 PR。

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
the readme tells, tap0901 not supported in windows yet
