### ISSUE TITLE
如何转发到目的地，而不是特定远程socks？

### ISSUE THREAD

**Issue by caobug** [eycorsican/go-tun2socks#25]
我的socks5服务器在本地127.0.0.1运行，它内部实现了ACL，部分访问不会通过特定的远程socks走，而是直接连接目的地，这不会造成死循环吗？

正常的：tun->本地socks->路由->旁路->eth0->远程目的地
死循环：tun->本地socks->路由->未旁路->tun..

**Comment by eycorsican** [comment]
这要看 TUN 是什么实现，一般 TUN/TAP driver 建立的 TUN 接口，要直接发到目的主机，就要在系统路由表里加相应的路由

**Comment by caobug** [comment]
谢谢解答。如果按地域分，国内的全部通过socks直连，而国外的网站才需要通过SOCKS转发到远程呢，那不是每次连接国内网站前都需要动态配置路由吗？
