### ISSUE TITLE
I want a Socks5 implementation of Username / Password.

### ISSUE THREAD

**Issue by BeOB** [eycorsican/go-tun2socks#26]
Hi
Your program is the best.
I want a Socks5 implementation of Username / Password.
is it possible?
Thank you

**Comment by eycorsican** [comment]
See #19

**Comment by BeOB** [comment]
go-tun2socks can't connection but SocksCap64 can connection.

error message: 
v2ray.com/core/app/proxyman/outbound: failed to process outbound traffic > v2ray.com/core/proxy/socks: failed to establish connection to server > v2ray.com/core/proxy/socks: auth method not supported.

Help me....

**Comment by eycorsican** [comment]
@BeOB https://github.com/v2ray/v2ray-core/issues/1459
