### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by luckypoem** [eycorsican/go-tun2socks#27]
hi。
cd $GOPATH
go get github.com/eycorsican/go-tun2socks/cmd/tun2socks
cd $GOPATH/src/github.com/eycorsican/go-tun2socks
go get -d ./...
make clean 
make build

在make build这步遇错：
...
github.com/eycorsican/go-tun2socks/core
v2ray.com/core/common/net
# v2ray.com/core/common/net
../../../../../v2ray.com/core/common/net/system.go:11:21: undefined: net.ListenConfig
github.com/eycorsican/go-tun2socks/proxy/echo
github.com/eycorsican/go-tun2socks/proxy/shadowsocks
github.com/eycorsican/go-tun2socks/proxy/socks
make: *** [Makefile:88: build] Error 2
root@wh:~/go/gopath/src/github.com/eycorsican/go-tun2socks#

如何解决？

**Comment by eycorsican** [comment]
Go 版本太低
