### ISSUE TITLE
routing

### ISSUE THREAD

**Issue by malikshi** [eycorsican/go-tun2socks#28]
released exec windows still using ip route Linux by default?, 
2019/01/14 23:35:32 device name: Ethernet 2
2019/01/14 23:35:33 set Ethernet 2 with net/mask: 240.0.0.2/255.255.255.0 through DHCP
2019/01/14 23:35:33 set Ethernet 2 with dns: 114.114.114.114,223.5.5.5 through DHCP

**Comment by eycorsican** [comment]
Sorry, I don't get your point.

**Comment by malikshi** [comment]
C:\Users\ibnum\Downloads\tun2socks-windows-4.0-amd64.exe\build\t2s.exe -tunName Ethernet 2 -tunAddr 10.0.0.2 -tunGw 10.0.0.1 -proxyType socks -proxyServer 127.0.0.1:1080

127.0.0.1:1080
route add 0.0.0.0 mask 0.0.0.0 10.0.0.1 metric 6
route add a.b.c.d 192.168.43.1 metric 5
after running it wont tunneled via tap,

**Comment by eycorsican** [comment]
Seems you are not correctly setting up the TUN device, you must install `Tap-windows` in order to create a TUN device on Windows: https://github.com/eycorsican/go-tun2socks#windows
