### ISSUE TITLE
LWIP编译失败

### ISSUE THREAD

**Issue by 50611** [eycorsican/go-tun2socks#3]
from ../../lwip/input.go:5:
../../lwip/src/include/lwip/arch.h:119: error: redefinition of typedef 'u8_t'
../../lwip/src/include/arch/cc_others.h:46: note: previous declaration of 'u8_t' was here
../../lwip/src/include/lwip/arch.h:120: error: redefinition of typedef 's8_t'
../../lwip/src/include/arch/cc_others.h:47: note: previous declaration of 's8_t' was here
../../lwip/src/include/lwip/arch.h:121: error: redefinition of typedef 'u16_t'
../../lwip/src/include/arch/cc_others.h:48: note: previous declaration of 'u16_t' was here
../../lwip/src/include/lwip/arch.h:122: error: redefinition of typedef 's16_t'
../../lwip/src/include/arch/cc_others.h:49: note: previous declaration of 's16_t' was here
../../lwip/src/include/lwip/arch.h:123: error: redefinition of typedef 'u32_t'
../../lwip/src/include/arch/cc_others.h:50: note: previous declaration of 'u32_t' was here
../../lwip/src/include/lwip/arch.h:124: error: redefinition of typedef 's32_t'
../../lwip/src/include/arch/cc_others.h:51: note: previous declaration of 's32_t' was here

能否提供个windows下的 makefile .谢谢

**Comment by eycorsican** [comment]
@50611 可以再试一下，我没在 Windows 上编译过，如果还不行可以用 `xgo` 来编译

**Comment by dogfight360** [comment]
Centos7环境下编译成功
[root@DC05R02DS25-03 go-tun2socks]# cd build/
[root@DC05R02DS25-03 build]# ls
tun2socks-darwin-10.6-amd64  tun2socks-linux-amd64  tun2socks-windows-4.0-amd64.exe


yun install docker -y
service docker start
docker pull karalabe/xgo-latest

go get github.com/karalabe/xgo
go get github.com/eycorsican/go-tun2socks

cd $GOPATH/src/github.com/eycorsican/go-tun2socks

xgo

make release

**Comment by eycorsican** [comment]
支持 UDP，你要有个支持 UDP 的服务器和正确设置 DNS，具体什么情况建议你抓包看看
