### ISSUE TITLE
udp是从socks代理出去的吗

### ISSUE THREAD

**Issue by zhaoguomanong** [eycorsican/go-tun2socks#30]
./build/tun2socks -tunName tun1 -tunAddr 240.0.0.2 -tunGw 240.0.0.1 -proxyType socks -proxyServer 127.0.0.1:1080

socks是v2ray的inbound.

发现跑起来后可以正常访问谷歌等外网，icmp ping也可以ping通墙外，但是测试udp的时候不通

我用
dig @8.8.8.8 www.google.com
测试的，一直超时

由于懒得动原来电脑上v2ray的json文件，把v2ray当socks类型的代理用，直接用你的tun2socks socks类型的handler.

这个版本的tun2socks udp转发默认就支持吗？需要特殊设置吗？比如原版badvpn-udpgw

**Comment by zhaoguomanong** [comment]
由于懒得动v2ray的json文件，想直接用你的tun2socks的 socks类型的handler.

**Comment by eycorsican** [comment]
你的v2 socks inbound有开udp？有正确配置里面的ip项？例子看 #16

**Comment by zhaoguomanong** [comment]
非常感谢，原因就是v2ray socks inbound　忘记打开udp支持了．

可以考虑在readme文档里面说下udp需要socks 也同时支持udp才行．

**Comment by cary-zhou** [comment]
那么tun2socks是否支持udp，需要调用udpgw吗？
