### ISSUE TITLE
是否存在比较严重内存泄漏问题

### ISSUE THREAD

**Issue by godla** [eycorsican/go-tun2socks#31]
是否存在比较严重内存泄漏问题
只有增长没有，释放，ios的ss代码

**Comment by godla** [comment]
目前使用的最新代码没有 进行任何 golang gc 方面的调整，奔溃的速度比之前更快了，就在刚刚我测试了下

**Comment by godla** [comment]
经过一些调整，发现并发下，线程数超过20，一定会奔溃

**Comment by eycorsican** [comment]
我并没发现类似问题，或者你看看这里的相关讨论：
https://github.com/eycorsican/go-tun2socks-ios/issues/2

**Comment by godla** [comment]
> 我并没发现类似问题，或者你看看这里的相关讨论： [eycorsican/go-tun2socks-ios#2](https://github.com/eycorsican/go-tun2socks-ios/issues/2)

正如你指引的连接秒速一样，上行测试 奔溃谢谢
