### ISSUE TITLE
建议增加一个Fake DNS的功能

### ISSUE THREAD

**Issue by xjasonlyu** [eycorsican/go-tun2socks#32]
有个想法，tun2socks进程监听53端口，并对dns查询回复如124.0.0.1之类的唯一的internal IP，然后将124.0.0.1的tcp连接或者udp包直接以socks5 domian的类型转发给socks server，就避免了dns 污染或者自建dns server的麻烦。

**Comment by eycorsican** [comment]
我不太理解你的意思。

首先 tun2socks 的最普通的用法就是全局代理转发，所有流量（包括 DNS）都转到代理服务器处理，只要代理服务器没染污就不会有染污问题。

其次 go-tun2socks 的 V2Ray handler 已经有一个比较好的可以处理大部分 DNS 染污问题的方案，而且我个人认为要优于你所说的 fake dns 方案。

**Comment by xjasonlyu** [comment]
- 如果在只有socks代理可用的时候，DNS污染解决就不太理想了
- 全局代理转发的时候，代理服务器只是转发dns的udp包，然后代理服务器就不能根据domian来进行rules分流，因为代理服务器收到的只有ip。

**Comment by eycorsican** [comment]
如果你想在中转服务器上根据域名对流量做进一步分流，可以了解一下 v2ray 的 sniffing/domainOverride 功能

**Comment by eycorsican** [comment]
以及 v2ray 刚出来的 dns outbound 功能

**Comment by eycorsican** [comment]
这些方案都比较优雅，只是做流量的转发，不会像fake dns 那样破坏本地 dns 缓存

**Comment by xjasonlyu** [comment]
但是我需要在自己的socks代理服务器上用，而不是v2ray

**Comment by xjasonlyu** [comment]
fake DNS 是在surge的ios tun和mac enhanced mode上用的，感觉挺简单粗暴的，不过不需要监听53做server，直接嗅探dns包然后更改记录的

**Comment by eycorsican** [comment]
你可以用内置在 go-tun2socks 里的 v2ray handler，然后配置个 socks outbound 啊，一样可以拦截分流 DNS
请求，默认也开了 sniffing，会带上域名给中转服务器

**Comment by xjasonlyu** [comment]
好像是可行的，我去试试，谢谢大佬

**Comment by eycorsican** [comment]
我又想了下，Fake DNS 还是有一定好处的，比如在服务器不支持 UDP 的情况下，SOCKS/Shadowsocks 之类的协议在全局情况下就没法工作了，用了 Fake DNS 的话虽然其它 UDP 流量还是无法工作，但域名解析可以正常工作，大部分的上网操作都不影响，所以这个功能我会考虑一下加上去。

**Comment by xjasonlyu** [comment]
是的，感觉Fake DNS在很多情况下都是挺好用的，虽然可以用`dns2socks`之类的方案解决socks server仅支持tcp的情况，但是并不是所有public DNS都支持dns over tcp的，所以Fake DNS在这点上的确有用（其实这样就可以给`tun2socks`加入HTTP Proxy支持了，直接`CONNECT`方法裸连问题也不大）

而且像我这种懒得去配置DNS的懒人也少了很多麻烦😂😂【比如Surge MAC下的Enhanced Mode就可以通过将`Gateway & DNS`设置成mac的ip就可以用来代理同网段下的device，我现在的linux解决方案还是 linux ip_forward + tun2socks + v2ray（但v2要配置得比较详细才能解决dns poison和分流问题，有fake dns就可以无脑交给v2内置路由解决了）】

好像已经有一些Fake DNS应用项目了：e.g. [KONE](https://github.com/xjdrew/kone)

**Comment by xjasonlyu** [comment]
其实只要对A和AAAA记录进行`example.com -> 198.18.0.1`之类的修改和mapping就好了，其他的查询可以考虑直接转发的。

然后其实也不一定要做DNS server，也可以对udp包检测（假设只是传统dns）是否是dns协议，是的话直接给fake dns handler就好了，这样的好处就是不需要手动修改dns设置了。所以建议可以的话，在fake dns加一个`dns劫持`的option。

**Comment by eycorsican** [comment]
用 V2Ray 配置出 Fake DNS 效果：https://github.com/v2ray/discussion/issues/24

**Comment by eycorsican** [comment]
想起来outline还采用了另一种方式来解决服务器不支持UDP的情况，就是 force DNS over TCP

**Comment by alalamav** [comment]
I have implemented a DNS fallback over TCP in #42.

**Comment by eycorsican** [comment]
master 上已经在 socks 和 shadowsocks 中支持 fake dns

**Comment by fbion** [comment]
https://github.com/FlowerWrong/tun2socks
这个支持fake dns

**Comment by fbion** [comment]
提供一种电脑做网关的思路

可以的
https://github.com/FlowerWrong/tun2socks
https://github.com/xjasonlyu/tun2socks
这两个已经实现fake dns
surge增强模式也是这样
有两种方式
google.com -> 192.18.0.1
google.com.hk -> 192.18.0.2

google.com -> 192.18.0.1:1111
google.com.hk -> 192.18.0.2:1112

通过这种关联即可

个人系统192.168.1.2开启
net.inet.ip.forwarding=1
开启tun2socks
sudo route add 198.18.0.2/24 240.0.0.1(tun网关)

手机设置网关192.168.1.2
所有流量走192.168.1.2了吧
192.168.1.2开启fake dns
手机dns服务器也设置为1.2
手机访问google.com 得到ip 192.18.0.1
手机连接192.18.0.1经过192.168.1.2
192.18.0.1走tun接口
tun2socks检测到访问192.18.0.1->google.com

此时tun2socks->v2ray inbounds
由v2ray来识别国外国内 google facebook twitter等域名

假如手机访问baidu,v2ray直接识别为geosite:cn ip 流量直接国内走


tun2socks只需要提供fake dns和代理功能
分流交给v2ray来做
这样
