### ISSUE TITLE
tun2socks 怎么关闭dns缓存？

### ISSUE THREAD

**Issue by xjasonlyu** [eycorsican/go-tun2socks#34]
需要关闭tun2socks的dns cache，有时候dns cache更新太慢了

**Comment by eycorsican** [comment]
没有关闭选项。缓存时间按DNS结果中的TTL来，跟系统缓存没啥不同，为什么会觉得慢呢？

**Comment by xjasonlyu** [comment]
其实是想自己控制dns cache

**Comment by eycorsican** [comment]
v1.11.2 中已加入 `-disableDNSCache`
