### ISSUE TITLE
关于ipv6

### ISSUE THREAD

**Issue by trump3000** [eycorsican/go-tun2socks#4]
测试发现  ipv6 数据包处理后并没用回调到 TCPAcceptFn，不知道如果添加IPv6 支持的话，lwip是否也也需要做一些改动。
//export TCPAcceptFn
func TCPAcceptFn(arg unsafe.Pointer, newpcb *C.struct_tcp_pcb, err C.err_t) C.err_t {...}

**Comment by eycorsican** [comment]
@trump3000 要添加 IPv6 支持，需要在 lwip 源码中做一点点修改，然后在 Go 中对传过来的 IPv6 地址做下处理，大概就可以。主要思路是使 lwip 原来的路由功能无效化，把输入到 lwip 的数据包全部转到环回接口，参考下 IPv4 的处理：https://github.com/eycorsican/lwip/blob/master/lwip-2.0.3/src/core/ipv4/ip4.c

**Comment by eycorsican** [comment]
除了 Windows 外，已支持 IPv6，如果需要 Windows IPv6 支持可以开新 issue。
