### ISSUE TITLE
请问lwip在tun2socks的作用是什么？

### ISSUE THREAD

**Issue by liange** [eycorsican/go-tun2socks#41]
请问lwip在tun2socks的作用是什么？

**Comment by eycorsican** [comment]
提供一个TCP/IP协议栈

**Comment by liange** [comment]
我的意思是 网络数据是通过lwip发送和接收的吗，还是通过操作系统的socket？
是这么一个流程tun <--> lwip  <-->internet 还是 tun --> lwip --> sys socket --> internet

**Comment by eycorsican** [comment]
后者

**Comment by liange** [comment]
那这个协议栈作用是啥呢，消息报的解析、修改、重组？

**Comment by eycorsican** [comment]
对
