### ISSUE TITLE
Module compatibility

### ISSUE THREAD

**Issue by alalamav** [eycorsican/go-tun2socks#45]
go modules are not writable when downloaded to `$GOPATH/mod/`. For this reason, the `make copy` action, which copies LWIP header and source files for every build action, is not compatible with go modules, when go-tun2socks is used as a dependency.

* What is the motivation for copying the LWIP files?
* Would it be possible to include them directly from the LWIP directory?

Thanks.

**Comment by eycorsican** [comment]
@alalamav Try [v1.13.2](https://github.com/eycorsican/go-tun2socks/commit/bfd274af8e227564ec9f310d793584a2646a4305), copying C source files is no longer needed.

**Comment by alalamav** [comment]
Thank you for the quick fix, it's working great!
