### ISSUE TITLE
macOS无法指定tunName

### ISSUE THREAD

**Issue by vivahu** [eycorsican/go-tun2socks#48]
使用 `./build/tun2socks -tunName tun1` 命令指定名称创建新TUN后，指定的名称不生效。仍然按照系统自带的utunx命名（其中x为递增正整数）

macOS版本：10.14.4

**Comment by eycorsican** [comment]
tun 这块用了 `github.com/songgao/water` ，需要它那边支持，而且就算支持了，在 macOS 上也只能用 utunX 这种名字，不能随意命名
