### ISSUE TITLE
这个无法用于UDP的游戏呢。。例如吃鸡和 csgo。。TCP 的都正常

### ISSUE THREAD

**Issue by 50611** [eycorsican/go-tun2socks#5]
网页 DNS 解析都正常。但是 cogo 和吃鸡。。都进不去游戏

**Comment by eycorsican** [comment]
@50611 大概修好了，但我并没测试过

**Comment by dogfight360** [comment]
@eycorsican 
之前支持测试过DNS跟nat是正常的.不过没试过游戏
更新刚刚的fix socks udp后试了下.顺便网卡抓包大概是这样的
吃鸡(游戏自带显示延迟1000多ms,封包倒是有来有回,但是速率低级,进入游戏后没法正常互动,过一会自动掉线)
战地1(UDP封包有去无回,无法进入游戏)
CSGO(能正常匹配进入,游戏内延迟会越来越高.达到2000ms左右.然后在1500-2000ms之间一上一下的徘徊)

**Comment by eycorsican** [comment]
@dogfight360 又修了一下，另外新增了 Shadowsocks 代理

**Comment by dogfight360** [comment]
游戏已经没有问题

提两个建议

1.ICMP不要直接回复,有个10-30ms的延迟.因为有些游戏延迟是0ms是检测失败.有些会当成外挂直接T掉

2.丢弃一些内网/广播的IP段的封包,否则如果出现广播封包/一些程序不停往这些地址发包会CPU起飞
前3个内网可选,不在路由表内的情况下是不会发到tun2socks里的.后2个是组播地址.建议禁止
10.0.0.0/8
172.16.0.0/12
192.168.0.0/24
224.0.0.0/8
239.255.255.250/32

**Comment by chenyue404** [comment]
这个东西在windows上具体怎么使用啊？哪里有相关教程呢？
