### ISSUE TITLE
Exit when computer wake up from sleep

### ISSUE THREAD

**Issue by dizzam** [eycorsican/go-tun2socks#50]
**OS Environment:** Windows 10 Pro Version 1809 (Build 17763.316)

**Step to Reproduce the Issue:**
1. Install the TAP-Windows Adapter (Version 9.22.1-I602)
2. Run tun2socks with `tun2socks -tunAddr 10.0.0.2 -tunGw 10.0.0.1 -proxyType socks -proxyServer <my socks server> -tunDns <mydns>`. All things go well and the computer can access the internet through `<my socks server>`.
3. Sleep the laptop.
4. Wake the laptop after a while.
5. tun2socks exit with: *copying data failed: The I/O operation has been aborted because of either a thread exit or an application request.*

**Expected Behavior:** tun2socks should continue running and attempt to recover all the stuff after waking up the computer.

Thank you very much!

*Edited:*
After testing, I guess this issue is because windows closed the Virtual Adapter when computer goes to sleep. Because when I manually disable the virtual adapter, tun2socks will quit with the same behavior. So I suggest to add a `-daemon` or `-service` option which can force tun2socks continue running even if there is no suitable adapter and trying to reconnect when the adapter is set up.

**Comment by dizzam** [comment]
As a workaround, I add a scheduled task triggered by "System: Power-Troubleshooter: Event ID 1", which restart tun2socks automatically after computer wake up. And this solve the issue temporarily.

**Comment by eycorsican** [comment]
It's much easier do the job in a wrapper app: https://github.com/eycorsican/Mellow/blob/c62542de83005549cd1c1ddd2542de62f464dac3/main.js#L85
