### ISSUE TITLE
It seems v2ray.com/core import path is broken

### ISSUE THREAD

**Issue by notedit** [eycorsican/go-tun2socks#51]
https fetch failed: Get https://v2ray.com/core/app/proxyman/inbound?go-get=1: x509: certificate is valid for *.gridserver.com, gridserver.com, not v2ray.com
build github.com/eycorsican/go-tun2socks-ios/go-tun2socks/cmd/tun2socks: cannot find module for path v2ray.com/core

go get  github.com/v2ray/v2ray-core  works fine.

**Comment by eycorsican** [comment]
V2ray.com is blocked by THE FIREWALL, I guess you need a proxy to get the
source.

**Comment by notedit** [comment]
I  already  have a proxy,   I can visite v2ray.com.

**Comment by eycorsican** [comment]
Your browser may be able to access v2ray.com, but your command line
utilities perhaps not...

**Comment by notedit** [comment]
I use a global proxy.
