### ISSUE TITLE
如果使用ss的本地socks5代理貌似不行

### ISSUE THREAD

**Issue by epth** [eycorsican/go-tun2socks#53]
route add 0.0.0.0 mask 0.0.0.0 10.0.0.1 metric 6
route add  127.0.0.1 192.168.0.1 metric 5
.\tun2socks-windows-4.0-amd64.exe  -tunAddr 10.0.0.2 -tunGw 10.0.0.1 -proxyType socks -proxyServer 127.0.0.1:1080
#127.0.0.1:1080为shadowsocks客户端侦听的端口

以上三个命令执行完之后就上不了网了，看了网卡状态信息都没问题!!

使用远程的shadowsocks服务端代理
.\tun2socks-windows-4.0-amd64.exe  -tunAddr 10.0.0.2 -tunGw 10.0.0.1 -proxyType socks -proxyServer x.xxx.xx.x8:1111 -proxyCipher CHACHA20-IETF -proxyPassword xxxx -proxyType shadowsocks
没有问题

**Comment by epth** [comment]
搞错了，能上，执行顺序的问题

**Comment by epth** [comment]
还是不行，总有问题，时断时续，而且特别慢，怀疑是127.0.0.1和udp2raw等冲突引起的

**Comment by eycorsican** [comment]
SOCKS5 proxy should works.

Please open another issue if you still encounter problems concerning performance, together with related configurations and logs.
