### ISSUE TITLE
可以编译成dll吗？

### ISSUE THREAD

**Issue by mkx1269173252** [eycorsican/go-tun2socks#54]

**Comment by eycorsican** [comment]
http://lmgtfy.com/?q=golang+build+dll

**Comment by cary-zhou** [comment]
我编译了一个dll动态链接库，有没有人给测试一下C#能否正常调用
[tun2socks.zip](https://github.com/eycorsican/go-tun2socks/files/3560929/tun2socks.zip)
以下为函数声明：
![捕获](https://user-images.githubusercontent.com/12585727/64040616-07e9c200-cb90-11e9-8750-9e3c1adbeb81.PNG)

**Comment by fivetime** [comment]
> 我编译了一个dll动态链接库，有没有人给测试一下C#能否正常调用
> [tun2socks.zip](https://github.com/eycorsican/go-tun2socks/files/3560929/tun2socks.zip)
> 以下为函数声明：
> ![捕获](https://user-images.githubusercontent.com/12585727/64040616-07e9c200-cb90-11e9-8750-9e3c1adbeb81.PNG)

你好，可以将你这个导出dll的代码开源出来吗？我想生成一个最新版的32位dll
