### ISSUE TITLE
貌似nat有问题？

### ISSUE THREAD

**Issue by dksslq** [eycorsican/go-tun2socks#56]
用go-tun2socks玩gta5，在线好友显示为不在线，网络信息显示'nat不可用，udp可能遭禁用'

**Comment by raintean** [comment]
你的代理支持UDP吗?

**Comment by dksslq** [comment]
v2ray,  不支持udp？，gta5是udp，如果不支持，那我游戏都上不去的，可是我上去了，就是看好友都是离线(错误的)

**Comment by eycorsican** [comment]
V2ray对UDP支持不好，主要有两方面，一是它自己所提出的VMess协议对UDP支持不好，二是整个代码实现上对UDP支持不够好，导致它所实现的SS也一同没法支持好UDP。
