### ISSUE TITLE
增加 Socks5 认证支持

### ISSUE THREAD

**Issue by hacking001** [eycorsican/go-tun2socks#57]
你好，请问能给 Socks5 增加认证支持吗？

我认为这添加起来非常简单：
- [https://godoc.org/golang.org/x/net/proxy#Auth](https://godoc.org/golang.org/x/net/proxy#Auth)
- [https://godoc.org/golang.org/x/net/proxy#SOCKS5](https://godoc.org/golang.org/x/net/proxy#SOCKS5)

我是 [x2tap](https://github.com/hacking001/x2tap) 项目的开发者，目前使用中需要增加一个 Socks5 认证支持

**Comment by eycorsican** [comment]
You're welcomed to create a PR for this feature.

It's may not as easy as you think since the SOCKS5 proxy implemented by `golang.org/x/net/proxy` lacks UDP associate support.

**Comment by hacking001** [comment]
I don't understand Go language.

I think this feature requires you to increase

(using Google Translate)

**Comment by hacking001** [comment]
my project removed, so this issue does not exist anymore.

**Comment by huapox** [comment]
+1

cur using: https://github.com/cooolinx/docker-socks5, which UDP is supported. (tested with SSTap)
