### ISSUE TITLE
关于速度问题请教

### ISSUE THREAD

**Issue by baggiogogo** [eycorsican/go-tun2socks#58]
用pve虚拟了两台linux，一台v2ray，一台go-tun2socks。
单独v2ray---------->目标vps，200M带宽跑满没问题，go-tun2socks-------->v2ray--------->目标vps，只能到65M上下。机器性能应该不存在瓶颈，请教可能是哪的问题，谢谢！

**Comment by Fndroid** [comment]
CPU问题？

**Comment by baggiogogo** [comment]
应该不是，J3455，我觉得200M应该不是问题。

**Comment by eycorsican** [comment]
单连接上行约 660Mbps，下行约 1.5Gbps。
10 个并发连接上行跟单连接差不多，下行约 2.5Gbps。

上行也可以优化到 1.5Gbps（自从引入[这个改变](https://github.com/eycorsican/go-tun2socks/commit/643323f74acf9303cc64139ff5413945107bc9f0)后变成 660Mbps），但要在代码实现上做些妥协。
 
测试方法看这里：https://github.com/eycorsican/go-tun2socks/blob/d0d16ba3c64f196ac4e2c1c1421cbe2296ba7055/proxy/redirect/tcp.go#L11

测试的 CPU 忘记是啥，应该差不多 i7 最高性能那个。
