### ISSUE TITLE
tun2socks-windows-4.0-amd64.zip的V1.4版本源码存在问题

### ISSUE THREAD

**Issue by FabioPLA** [eycorsican/go-tun2socks#6]
![image](https://user-images.githubusercontent.com/26806814/47482944-8b4ccf80-d86a-11e8-9b26-ec69f0760f7f.png)
C:\Users\xiaoj\Desktop\tun2socks-windows-4.0-amd64>tun2socks-windows-4.0-amd64.exe -help
Assertion "CryptGenRandom failed" failed at line 55 in sys_arch.c

C:\Users\xiaoj\Desktop\tun2socks-windows-4.0-amd64>

**Comment by eycorsican** [comment]
Fixed.
