### ISSUE TITLE
windows下：无法打开设备文件

### ISSUE THREAD

**Issue by zhengfangxin** [eycorsican/go-tun2socks#60]
版本：1.15.0
日志如下：
2019/06/06 17:46:43 device component id: {384A80A1-8641-4E42-BF20-EEC6094706BB}
2019/06/06 17:46:43 device name: 以太网 2
2019/06/06 17:46:44 failed to open tun device: The system cannot find the file specified.

我看是这个文件名字：\\.\Global\%s.tap
这个文件路径是怎么得来的呢？

**Comment by cpu100** [comment]
解决了吗
