### ISSUE TITLE
windows下socks类型连接127.0.0.1的会崩溃

### ISSUE THREAD

**Issue by patrickwangqy** [eycorsican/go-tun2socks#63]
我本地v2ray开了一个socks端口，然后tun2socks打开就会崩溃
命令如下
tun2socks.exe -tunName tap0 -tunAddr 10.0.0.2 -tunGw 10.0.0.1 -proxyType socks -proxyServer 127.0.0.1:1080
![image](https://user-images.githubusercontent.com/22412010/59324973-bf023a00-8d13-11e9-8bc1-fbc476211a53.png)

**Comment by eycorsican** [comment]
https://github.com/eycorsican/go-tun2socks/issues/64#issuecomment-501531888
