### ISSUE TITLE
请教一个代码编译中出现的问题

### ISSUE THREAD

**Issue by FabioPLA** [eycorsican/go-tun2socks#7]
![image](https://user-images.githubusercontent.com/26806814/47626490-568c9100-db66-11e8-96e8-47d1d6b6ec24.png)
一直想不明白这个编译出现的问题，请教一下这个如何解决，谢谢

**Comment by eycorsican** [comment]
1、升级 Go 到最新版本
2、`go build` 之前需要一些额外构建步骤（C 源文件复制），所以不能直接用 `go build`，用 `make`。其实复制文件也很简单，手动复制了的话也可以不用 `make`：https://github.com/eycorsican/go-tun2socks/blob/fa05fbf2b87d5530cefbf26b386a5c0da784a4f8/Makefile#L57
