### ISSUE TITLE
socks5代理UDP问题

### ISSUE THREAD

**Issue by wuli07101** [eycorsican/go-tun2socks#75]
依socks5协议，proxy/socks/udp.go中resolvedAddr应该为目的地，而conn.WriteFrom应该要用来远端地址吧？
RFC 1928                SOCKS Protocol Version 5              March 1996
      +----+------+------+----------+----------+----------+
      |RSV | FRAG | ATYP | DST.ADDR | DST.PORT |   DATA   |
      +----+------+------+----------+----------+----------+
      | 2  |  1   |  1   | Variable |    2     | Variable |
      +----+------+------+----------+----------+----------+

     The fields in the UDP request header are:

          o  RSV  Reserved X'0000'
          o  FRAG    Current fragment number
          o  ATYP    address type of following addresses:
             o  IP V4 address: X'01'
             o  DOMAINNAME: X'03'
             o  IP V6 address: X'04'
          o  DST.ADDR       desired destination address
          o  DST.PORT       desired destination port
          o  DATA     user data

![image](https://user-images.githubusercontent.com/12413447/61517955-13978400-aa3b-11e9-99d2-fdcbe2839ed6.png)
![image](https://user-images.githubusercontent.com/12413447/61518348-e0a1c000-aa3b-11e9-923c-3ca1b1e6c926.png)

**Comment by eycorsican** [comment]
通过 tun2socks 去代理请求是一种透明代理方式，比例说你访问 https://google.com ，在浏览器看来，remote/target/dest 都是 google.com 的服务器，在代理客户端程序（socks/shadowsocks 部分）看来，remote 是代理服务器，target/dest 是 google.com 服务器，在代理服务端程序看来，remote 是 代理客户端，target/dest 是 google.com 的服务器

**Comment by wuli07101** [comment]
### 数据响应的返回的时候，在代理服务端程序看来，remote应该是socks/shadowsocks吧，target/dest 应该是真实IP地面（非虚拟网卡）？
所以
![image](https://user-images.githubusercontent.com/12413447/61688627-1dc9c300-ad58-11e9-9dbb-268d1a3138a3.png)
读取的应该是手机的IP地址和端口？
