### ISSUE TITLE
socks5代理UDP DNS问题

### ISSUE THREAD

**Issue by wuli07101** [eycorsican/go-tun2socks#76]
如果使用socks5的UDP代理DNS解析会存在如下问题：
1、依socks5协议，UDP代理时会先建立TCP链接，但是DNS解析完后，UDP是没关闭的，导致TCP和UDP连接一直没关闭？
问题：是不是使用dnsfallback会更好，未发出udp,直接tcp?

2、是不是DNS走自己的DNS服务器，直接directr更好，在directr中实现FakeDns，这样省掉tcp握手,性能更好（暂不考虑dns污染）

![image](https://user-images.githubusercontent.com/12413447/61680790-7770c400-ad3d-11e9-82f9-1ccbdd4876cb.png)

我看ginuerzh/gost的实现是启动一个定时器，一段时间内没数据就主动关闭连接来避免太多连接没主动关闭的问题
![image](https://user-images.githubusercontent.com/12413447/61680954-18f81580-ad3e-11e9-851e-d200353cb25f.png)

**Comment by eycorsican** [comment]
没认真看代码。
