### ISSUE TITLE
failed to open tun device: No more data is available.

### ISSUE THREAD

**Issue by cpu100** [eycorsican/go-tun2socks#78]
Win10 
```
S:\Downloads\tun2socks-windows-4.0-amd64.exe>tun2socks-windows-4.0-amd64.exe -tunAddr 192.168.99.1 -tunGw 192.168.99.10 -proxyType socks0 -proxyServer 127.0.0.1:1080 --tunName "VirtualBox Host-Only Ethernet Adapter #2"
2019/08/14 13:07:54 failed to open tun device: No more data is available.
```
提示信息太少了，估计作废
```
S:\Downloads\tun2socks-windows-4.0-amd64.exe>tun2socks-windows-4.0-amd64.exe
2019/08/14 13:10:50 failed to open tun device: No more data is available.
```

**Comment by eycorsican** [comment]
w网卡禁用一下后再启用试试

**Comment by eycorsican** [comment]
n你指定的是tap-windows的虚拟网卡吗？

**Comment by cpu100** [comment]
是 VirtualBox 生成的虚拟网卡

**Comment by eycorsican** [comment]
n那大概不行，你用tun2socks是想干什么？

**Comment by cpu100** [comment]
网卡级别的全局代理

**Comment by eycorsican** [comment]
n那你用mellow吧

**Comment by cpu100** [comment]
我安装 tap-windows 再试试 tun2socks

**Comment by cpu100** [comment]
可以是可以，CPU占用率太高了，真的是100%了

**Comment by cpu100** [comment]
![image](https://user-images.githubusercontent.com/42709228/63004963-296b5e00-beae-11e9-8e27-ae2906b7777c.png)

**Comment by eycorsican** [comment]
y用mellow吧，每个系统都有些东西需要特殊处理，mellow都会处理好，你单用tun2socks很容易配置错

**Comment by atkdef** [comment]
May be a little bit late but here's one possible solution. 

For me, this error is caused by having spaces in the NIC name. Removing all the space characters by renaming the NIC should help. 

Hope this helps anyone who encounters such.

**Comment by mxvin** [comment]
Not necessary, it's also works by quoting interface name like `-tunName "Local Area Connection"` which is the default name of newly created TAP adapter
