### ISSUE TITLE
如何在iOS中使用？gomobile 编译后执行报错「operation not permitted」

### ISSUE THREAD

**Issue by uimeet** [eycorsican/go-tun2socks#8]
tun/* 目录中，并没有tun_ios.go的实现，使用gomobile编译后，在运行中执行到

```
#github.com/songgao/water/syscalls_darwin.go

if _, _, errno := syscall.RawSyscall(syscall.SYS_CONNECT, uintptr(fd), uintptr(addrP), uintptr(sockaddrCtlSize)); errno != 0 {
	err = errno
	return nil, fmt.Errorf("error in syscall.RawSyscall(syscall.SYS_CONNECT, ...): %v", err)
}
```

会返回错误「operation not permitted」

是否有什么变通的方式可以实现？

**Comment by eycorsican** [comment]
看起来你的是越狱设备？这个我并不清楚怎么做，ios 上可以编译成 framework 来用，ios 有 tun 的接口给你调

**Comment by uimeet** [comment]
如何调iOS 的 tun 接口呢？有不有文档或demo？多谢～～

**Comment by uimeet** [comment]
曾经越过狱，但是后来升级了系统，已经不是越狱设备了。

**Comment by eycorsican** [comment]
NEKit 了解一下：https://github.com/zhuhaow/NEKit

**Comment by eycorsican** [comment]
demo app 的话我后面或许会做一下吧，但没什么保证不要期待

**Comment by raintean** [comment]
@uimeet  不要尝试在iOS上使用这个库了,  tunnel packet provider有内存的限制, 目前是15M, golang做的framework很快就会超过这个限制

**Comment by uimeet** [comment]
@raintean 内存限制这个问题，我已经解决了

**Comment by uimeet** [comment]
@eycorsican 好的，多谢～

**Comment by uimeet** [comment]
@raintean 看上去解决了，正常使用方式测试了一天，没有崩溃，内存一直控制在14M以下。

**Comment by raintean** [comment]
@raintean  你怎么解决的?  如果是从go方面入手的话  目前我尝试过  pool化   手动强制GC  以及  返还申请的系统内存, 虽然也能稳定在15M以下,但是 太危险了  走钢丝的感觉

**Comment by raintean** [comment]
@uimeet 另外你可以尝试浏览一下youtube,大流量很容易爆掉

**Comment by uimeet** [comment]
@raintean 看视频不会崩，主要是看大体积的网页会崩，比如国内的各大门户网站。
差不多就是更积极的垃圾回收来解决内存增长问题。

**Comment by uimeet** [comment]
@eycorsican tun2socks也成功整合

**Comment by ameue** [comment]
> demo app 的话我后面或许会做一下吧，但没什么保证不要期待

早点出个demo吧
