### ISSUE TITLE
IPv6网关(tunGw)和IPv6地址(tunAddr)支持

### ISSUE THREAD

**Issue by Hiscriand** [eycorsican/go-tun2socks#81]
你好，我没能成功找到关于设置IPv6网关(tunGw)和IPv6地址(tunAddr)的相关文档
请问此程序是否支持IPv6，如果可以，是否能够与IPv4同时运行

目前的情况是，tun2socks运行后，IPv4走tun2socks，IPv6为电脑原本的IPv6地址

tun2socks-windows-4.0-amd64.exe -tunAddr "192.168.5.100" -tunGw "192.168.5.1" -proxyType "shadowsocks" -proxyServer "server_ip:5000" -proxyCipher "aes-256-cfb" -proxyPassword "password"

我是根据这个教程操作的：
https://medium.com/@TachyonDevel/%E6%95%99%E7%A8%8B-%E5%9C%A8-windows-%E4%B8%8A%E4%BD%BF%E7%94%A8-tun2socks-%E8%BF%9B%E8%A1%8C%E5%85%A8%E5%B1%80%E4%BB%A3%E7%90%86-aa51869dd0d

**Comment by eycorsican** [comment]
目前 Windows 上不支持 IPv6
