### ISSUE TITLE
Use of the -exceptionApps parameter(-exceptionApps参数怎么使用?)

### ISSUE THREAD

**Issue by zuoshouhub** [eycorsican/go-tun2socks#86]
Hello, I don't seem to have any effect when using the -exceptionApps parameter in the process.
I use it like this: -exceptionApps "test,Chrome" or -exceptionApps "test.exe,Chrome.exe"
I opened tun2socks and used test.exe and Chrome browser to view ip is not my original ip address but my proxy address
I see the explanation for this parameter as: "Exception app list separated by commas"
I understand that the application in this parameter should not go to the proxy. Is it that I understand it wrong or is my usage wrong?
---------------------------------------------------------------------------------------------------------
你好，我在使用tun2socks的时候用-exceptionApps这个参数好像没有作用？
我是这样用的:-exceptionApps "test,Chrome" 或者 -exceptionApps "test.exe,Chrome.exe" 
启动tun2socks后我用test.exe和Chrome浏览器查看ip地址是我的代理地址而不是我原本的地址
我看到此参数的解释为：例外应用列表，以逗号分隔
我理解为这个参数中的应用不会使用代理，不知道是我的理解错误了还是我的使用方法错误??

**Comment by eycorsican** [comment]
The option is no longer supported.
