### ISSUE TITLE
1.15.0版本运行崩溃

### ISSUE THREAD

**Issue by NikoBlack** [eycorsican/go-tun2socks#88]
运行大约30秒后崩溃，不同环境时间不同，但报错代码大概类似

![错误1](https://user-images.githubusercontent.com/45842900/67161917-c1dffc00-f391-11e9-82fa-e46dea67c0a4.png)
![错误2](https://user-images.githubusercontent.com/45842900/67161919-c1dffc00-f391-11e9-9f0a-8b261ea1344a.png)
![错误3](https://user-images.githubusercontent.com/45842900/67161921-c2789280-f391-11e9-9387-c892396aeb4e.png)
![错误4](https://user-images.githubusercontent.com/45842900/67161916-c1dffc00-f391-11e9-82d0-250d9043a97d.png)
![。。。。错误5](https://user-images.githubusercontent.com/45842900/67161936-c7d5dd00-f391-11e9-8408-d4260f0bd6d2.png)

**Comment by eycorsican** [comment]
I believe it had been fixed by the latest release.
