### ISSUE TITLE
内存增长太快，导致iOS Network Extension触发内存限制（15M）崩溃

### ISSUE THREAD

**Issue by ShuoHuang** [eycorsican/go-tun2socks#9]
作者你好！
导入库到iOS Network Extension中，启用后，只要有请求，内存就会增长，Network Extension有15M内存限制的问题，导致该进程被系统杀死。我们编译库时已开启go的内存回收功能，但是内存还是会增长，当然比不开启效果好一些。
请问你有什么好的方法处理这个问题吗？你在Kitsunebi这个APP中是怎么处理这个问题的呢？

**Comment by uimeet** [comment]
现在的问题应该是v2ray的实例化后内存就增加8-9m（此时还没有运行v2ray服务），这样留给实际运行的增长空间就很小了，如果可以压缩这个内存，实际上可以大大增加适用范围。

**Comment by VictoriaRaymond** [comment]
这8-9m是binary的大小吗？还是启动之后申请了这么多空间？如果能知道这些空间的用途，可能可以优化掉。

**Comment by uimeet** [comment]
是运行内存直接增加了这么多，我测试过在PacketTunnel中不实例化v2ray的情况下，内存占用是3.2M左右，一旦实例化v2ray，哪怕不做任何操作，启动PacketTunnel内存直接上升到11.x-12M的样子。

**Comment by uimeet** [comment]
纠正一下上条评论的不严谨之处，并不是实例化v2ray内存上升，而是实例化我自己的一个struct，初始化了其中两个字段，一个类型为sync.Mutex，一个类型为struct（这个struct包含一个bool字段和一个v2ray的core.Server字段，实例化这个struct的时候，还没有实例化v2ray），就是这样内存就上升到11-12m的水平了。

**Comment by uimeet** [comment]
我gomobile编译出的framework，经过测试在swift中import进来时（不做任何方法调用），此时内存正常，一旦调用里面的任意方法，哪怕这个方法不做任何处理直接return nil，内存也要增加8-9m.

**Comment by VictoriaRaymond** [comment]
你可以看一下Golang的内存占用，大概是这样：

```go
{
  var memstats runtime.MemStats
  runtime.ReadMemStats(&memstats)
  fmt.Printf("1: %+v\n", memstats)
}
```

读一段较大（比如有geoip之类）的配置之后，HeapInUse有大约6M，然后调用runtime.GC()之后，HeapInUse会降到2M以下。

如果确认是GC的问题，你可以设置 [GOGC 环境变量](https://golang.org/pkg/runtime/#hdr-Environment_Variables)来加速GC的触发。GC之后你可能还需要调用debug.FreeOSMemory()把内存还给系统（Golang的默认归还周期是五分钟）。

**Comment by uimeet** [comment]
@VictoriaRaymond 感谢回复，立即测试了，效果不大。

**Comment by ShadowRayEN** [comment]
> 这8-9m是binary的大小吗？还是启动之后申请了这么多空间？如果能知道这些空间的用途，可能可以优化掉。

只启动NetworkExtension，2.5M左右
NetworkExtension+Go（最简单的打印调用），4.8M左右
NetworkExtension+Go+V2Ray（什么都不启动），10M左右
增加的主要是加载到内存中的动态库，并非运行使用的内存。

**Comment by ShadowRayEN** [comment]
> 这8-9m是binary的大小吗？还是启动之后申请了这么多空间？如果能知道这些空间的用途，可能可以优化掉。

详情请参考：
[移动端移植：限制Inbound最大链接数 #79](https://github.com/v2ray/Planning/issues/79)

**Comment by eycorsican** [comment]
更详细的讨论看这里：https://github.com/eycorsican/go-tun2socks-ios/issues/2
