### ISSUE TITLE
How to build go-tun2socks + v2ray for Android?

### ISSUE THREAD

**Issue by ednew2018** [eycorsican/go-tun2socks#91]
Can you give a little demo and example code? Or just some explanation to the code base. 

I have no clue at all.

Thanks a lot.

**Comment by PterX** [comment]
you could read the page mobile project
https://github.com/eycorsican/go-tun2socks-mobile

**Comment by ednew2018** [comment]
@PterX Thanks. I know this project. But some part of the code either removed or deprecated. Plus the project kitsunebi-android. 

BTW, they are all good projects for the people.

**Comment by xxf098** [comment]
@ednew2018 checkout my [project](https://github.com/xxf098/go-tun2socks-build), works with the lastest version of v2ray-core and go-tun2socks

**Comment by ednew2018** [comment]
@xxf098 Awesome!! Does this also work on iOS?

**Comment by xxf098** [comment]
checkout the [Makefile](https://github.com/xxf098/go-tun2socks-build/blob/master/Makefile),  you can try with `make ios` to build for IOS.
