### ISSUE TITLE
set TCP and UDP forwarding separately

### ISSUE THREAD

**Issue by iugo** [eycorsican/go-tun2socks#94]
能否分别设置 TCP 和 UDP 的 SOCKS5 转发?

badvpn 的 Tun2socks 默认只转发 TCP, 可以加一个参数单独转发 UDP: https://github.com/ambrop72/badvpn/wiki/Tun2socks#udp-forwarding

**Comment by CsHeng** [comment]
难道不是只劫持tcp流量过来就可以了么？（用iptables的情况下）

**Comment by eycorsican** [comment]
你的意思是比如只代理 TCP，让 UDP 直接吗？理论上可以的，但不在这个项目功能范围。

**Comment by mastersani** [comment]
hello every one..
we are looking for udp to sock
